# httpproxy.yaml
{{- if .Values.ingress }}
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: canary-automation
  namespace: canary-automation
spec:
  virtualhost:
    fqdn: {{ .Values.fqdn }}
  routes:
    - conditions:
      - prefix: /
      services:
        - name: canary-automation-stable
          port: 5000
          weight: {{ .Values.stable_weight | default "100" }}
        {{ if .Values.canary_weight }}
        - name: canary-automation-canary
          port: 5000
          weight: {{ .Values.canary_weight }}
        {{ end }}
        {{ if .Values.baseline_weight }}
        - name: canary-automation-baseline
          port: 5000
          weight: {{ .Values.baseline_weight | default "0" }}  
        {{ end }}
{{- end }}
{{ - if .Values.linkerd }}
apiVersion: split.smi-spec.io/v1alpha2
kind: TrafficSplit
metadata:
  name: canary-automation
  namespace: canary-automation
spec:
  service: backend-svc
  backends:
  - service: backend-svc
    weight: 500
  - service: failing-svc
    weight: 500
{{- end }}