# httpproxy.yaml
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: canary-automation
  namespace: canary-automation
spec:
  virtualhost:
    fqdn: af8e2cb9bcd694fba84ccc0d3f205143-879495807.us-east-2.elb.amazonaws.com
  routes:
    - conditions:
      - prefix: /
      services:
        - name: canary-automation-canary-test
          port: 5000
