# httpproxy.yaml
{{- if .Values.ingress }}
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: canary-automation
  namespace: canary-automation
spec:
  virtualhost:
    fqdn: af8e2cb9bcd694fba84ccc0d3f205143-879495807.us-east-2.elb.amazonaws.com
  routes:
    - conditions:
      - prefix: /
      services:
        - name: canary-automation-stable
          port: 5000
          weight: {{ .Values.stable_weight | default "100" }}
        {{ if .Values.canary_weight }}
        - name: canary-automation-canary
          port: 5000
          weight: {{ .Values.canary_weight }}
        {{ end }}
        {{ if .Values.baseline_weight }}
        - name: canary-automation-baseline
          port: 5000
          weight: {{ .Values.baseline_weight | default "0" }}  
        {{ end }}
{{- end }}