name: "[WD] Execute Helm command"

on:
  workflow_dispatch:
    inputs:
      command:
        description: "helm command without helm"
        required: true
        default: "list -n canary-automation"

jobs:
  execute:
    runs-on: [ubuntu-latest]
    steps:
      - name: configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: us-east-2
      - name: execute command
        run: |
          aws eks update-kubeconfig --name canary-automation
          kubectl config set-context arn:aws:eks:us-east-2:801176112578:cluster/canary-automation
         
          helm ${{ github.event.inputs.command }}
