name: Build and Deploy

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v3

      - name: docker build
        run: |
          docker build . -t zyzlik/canary-automation:latest
      
      - name: login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: push
        run: |
          docker push zyzlik/canary-automation:latest
  deploy:
    runs-on: [ubuntu-latest]
    needs: [build]
    steps:
      - uses: actions/checkout@v3
      - name: configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: us-east-2
      - name: deploy
        run: |
          aws eks update-kubeconfig --name canary-automation
          kubectl config set-context arn:aws:eks:us-east-2:801176112578:cluster/canary-automation
         
          helm upgrade --install --create-namespace --cleanup-on-fail --atomic -n canary-automation canary-automation ./kubernetes 