name: Build and Deploy

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: [ubuntu-latest]
    needs: [build]
    steps:
      - uses: actions/checkout@v3
      - name: configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: us-east-2
      - name: deploy stable
        run: |
          aws eks update-kubeconfig --name canary-automation
          kubectl config set-context arn:aws:eks:us-east-2:801176112578:cluster/canary-automation
         
          # Deploy stable app
          helm upgrade --install --create-namespace \
          --cleanup-on-fail --atomic -n canary-automation \
          --set track=stable --set ingress=false \
          canary-automation-stable ./kubernetes 
